"""
Django settings for funding_project project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#83vf$qugojs09%cg!ygs=p=@c=&8)-1#l^5(pflgq5=s0*xy!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# For AWS deployment
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 
                 'ec2-13-211-152-223.ap-southeast-2.compute.amazonaws.com', 'uwa-fodb.ml']

# For AWS deployment
SETTINGS_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django_filters',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'fodb.apps.FodbConfig',
    'users.apps.UsersConfig',
    'crispy_forms',
    # google auth
    'social_django',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # google auth
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'funding_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(SETTINGS_PATH, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATE_DIRS = (
   # Put strings here, like "/home/html/django_templates" or "C:/www/django/templates".
   # Always use forward slashes, even on Windows.
   # Don't forget to use absolute paths, not relative paths.
   BASE_DIR + '../fodb/templates',
)

WSGI_APPLICATION = 'funding_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'fodb.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Australia/Perth'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'


CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = 'fodb-home'

LOGIN_URL = 'login'

# For AWS deployment
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

# Auth test
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'fodbdjangoauth@gmail.com'
EMAIL_HOST_PASSWORD = 'DjangoAuth2019'
EMAIL_PORT = 587

# google auth
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '1080830784114-i6d3q36pmfb6m4uvc1vn5nle395gnjme.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'skenPUpWLy8S120YKF0-2of_'

LOGIN_URL = '/auth/login/google-oauth2/'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


SOCIAL_AUTH_URL_NAMESPACE = 'social'

SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'hd': 'student.uwa.edu.au'
}
SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS = ['student.uwa.edu.au', 'uwa.edu.au']


# fixing auth forbidden error redirect
# see fodb/pipeline.py to change the url

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'fodb.pipeline.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

# Doesn't work as intended
''' 
SOCIAL_AUTH_LOGIN_ERROR_URL = '/error/'
SOCIAL_AUTH_BACKEND_ERROR_URL = '/error/'
RAISE_EXCEPTIONS = False
SOCIAL_AUTH_RAISE_EXCEPTIONS = False
'''


# ms auth
SOCIAL_AUTH_AZUREAD_OAUTH2_KEY = '913c0f24-ac27-4b05-833c-cb54b3d26cec'
SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET = 'cGA18B]5wmJu2[=VsfGogMxFst:s4qfC'

# ms auth 2
#SOCIAL_AUTH_AZUREAD_OAUTH2_KEY = '14410f03-ffec-42c1-878f-44bf90dbe48f'
#SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET = 'OuD6JzBH[PD6nkjAUUBekvWpcAt4]4[_'

# ms auth 3
#SOCIAL_AUTH_AZUREAD_OAUTH2_KEY = '4e8517a7-f23d-41de-b191-62ac4d5c5adf'
#SOCIAL_AUTH_AZUREAD_OAUTH2_SECRET = '.opqs90TtGT2X.oV0-A[G89pfUKNsVHF'


# uwa webmail login url:
'''
 https://login.microsoftonline.com/common/oauth2/authorize?client_id=00000002-0000-0ff1-ce00-000000000000
    &redirect_uri=https%3a%2f%2foutlook.office365.com%2fowa%2f&resource=00000002-0000-0ff1-ce00-000000000000
    &response_mode=form_post&response_type=code+id_token&scope=openid&msafed=0
    &client-request-id=72f89000-f8ab-4d1a-97ef-3c7e57715733
    &protectedtoken=true
    &domain_hint=uniwa.mail.onmicrosoft.com
    &nonce=637059448430510557.eac257b4-cc61-47d6-9adb-87a0707cfe77&state=DctLDoMwDEXRpF1IV5Bgip0HyzEGpEgNlvoR228G585uDCHcu1sXqSegTCBZmGeeSEYSQd7VnoKVk1kZE2MradFtTTOUQLBjB2J_H4NfOvzOemluWl_Zz1bt7R8_vtm8_QE
'''
# from this we can see the 'domain_hint' should be 'uniwa.mail.onmicrosoft.com':
SOCIAL_AUTH_AZUREAD_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'domain_hint': 'uniwa.mail.onmicrosoft.com'
}

SOCIAL_AUTH_AZUREAD_OAUTH2_WHITELISTED_DOMAINS = ['uwa.edu.au']

