# Generated by Django 2.2.4 on 2019-10-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funding_opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='none', max_length=100, verbose_name='Funding provider')),
                ('name', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=50000)),
                ('closing_date', models.DateTimeField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('link', models.URLField(max_length=260)),
                ('limit_per_uni', models.BooleanField(default=False, verbose_name='Limited Per University')),
                ('max_amount', models.IntegerField(blank=True)),
                ('max_duration', models.IntegerField(blank=True)),
                ('duration_type', models.CharField(choices=[('Y', 'year'), ('M', 'month')], max_length=6)),
                ('amount_estimated', models.BooleanField(default=False)),
                ('duration_estimated', models.BooleanField(default=False)),
                ('ecr', models.BooleanField(default=False)),
                ('travel', models.BooleanField(default=False)),
                ('visiting', models.BooleanField(default=False)),
                ('wir', models.BooleanField(default=False)),
                ('phd', models.BooleanField(default=False)),
                ('international', models.BooleanField(default=False)),
                ('hms', models.BooleanField(default=False, verbose_name='HMS')),
                ('ems', models.BooleanField(default=False, verbose_name='EMS')),
                ('science', models.BooleanField(default=False, verbose_name='SCI')),
                ('fable', models.BooleanField(default=False, verbose_name='FABLE')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Hidden from regular view')),
                ('External_deadline', models.DateTimeField(blank=True, null=True)),
                ('Forecast_Month', models.CharField(blank=True, choices=[('1', 'Jan'), ('2', 'Feb'), ('3', 'Mar'), ('4', 'Apr'), ('5', 'May'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'Aug'), ('9', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], max_length=15)),
                ('Internal_deadline', models.DateTimeField(blank=True, null=True)),
                ('EOI_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Expression of interest deadline')),
                ('Minimum_data_deadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Funding Opportunity',
                'verbose_name_plural': 'Funding Opportunities',
                'ordering': ['name'],
            },
        ),
    ]
