# Generated by Django 2.2.4 on 2019-09-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='important_date',
            name='milestone',
            field=models.CharField(max_length=200),
        ),
    ]
