# Generated by Django 2.2.4 on 2019-09-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding_Opportunity1',
            fields=[
                ('Opportunity_ID', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('Opportunity_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=2500)),
                ('HERDC', models.IntegerField(blank=True)),
                ('Closing_Month', models.DateTimeField()),
                ('Creation_Date', models.DateTimeField(auto_now=True)),
                ('Last_Updated', models.DateTimeField(auto_now_add=True)),
                ('Link', models.CharField(max_length=260)),
                ('limit_per_uni', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Boolean_Tags',
            fields=[
                ('Funding_Opportunity1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fodb.Funding_Opportunity1')),
                ('ECR', models.BooleanField(default=False)),
                ('Travel', models.BooleanField(default=False)),
                ('Visiting', models.BooleanField(default=False)),
                ('WiR', models.BooleanField(default=False)),
                ('PhD', models.BooleanField(default=False)),
                ('International', models.BooleanField(default=False)),
                ('HMS', models.BooleanField(default=False)),
                ('EMS', models.BooleanField(default=False)),
                ('Science', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('Funding_Opportunity1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fodb.Funding_Opportunity1')),
                ('Max_Amount', models.IntegerField(blank=True)),
                ('Max_Duration', models.IntegerField(blank=True)),
                ('Amount_Estimated', models.BooleanField(default=False)),
                ('Duration_Estimated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('Date_ID', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('Milestone', models.CharField(max_length=35)),
                ('Date', models.DateTimeField()),
                ('Date_Status', models.CharField(max_length=20)),
                ('Opportunity_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fodb.Funding_Opportunity1')),
            ],
        ),
    ]
