# Generated by Django 2.2.4 on 2019-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding_opportunity',
            name='duration_type',
            field=models.CharField(choices=[('Y', 'year'), ('M', 'month')], max_length=6),
        ),
    ]
