# Generated by Django 2.2.4 on 2019-10-11 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funding_opportunity',
            old_name='EOI_deadline',
            new_name='eoi_deadline',
        ),
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='External_deadline',
        ),
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='Forecast_Month',
        ),
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='Internal_deadline',
        ),
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='Minimum_data_deadline',
        ),
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='closing_date',
        ),
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='visiting',
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='application_open_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Application Open Date'),
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='external_submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='External Submission Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='forecast_month',
            field=models.CharField(blank=True, choices=[('1', 'Jan'), ('2', 'Feb'), ('3', 'Mar'), ('4', 'Apr'), ('5', 'May'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'Aug'), ('9', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], max_length=15, verbose_name='Forecast Month'),
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='internal_submission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Internal deadline'),
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible in regualr view'),
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='minimum_data_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Minimum data deadline'),
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='visiting_fellow',
            field=models.BooleanField(default=False, verbose_name='Visiting Fellow'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('Y', 'year'), ('M', 'month')], max_length=6),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='ecr',
            field=models.BooleanField(default=False, verbose_name='Early Career Research'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='ems',
            field=models.BooleanField(default=False, verbose_name='Engineering and Mathematical Sciences'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='fable',
            field=models.BooleanField(default=False, verbose_name='Faculty of Arts, Business, Law and Education'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='hms',
            field=models.BooleanField(default=False, verbose_name='Health and Medical Science'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='link',
            field=models.URLField(max_length=260, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='max_amount',
            field=models.IntegerField(blank=True, verbose_name='Max Amount'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='max_duration',
            field=models.IntegerField(blank=True, verbose_name='Max Duration'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='phd',
            field=models.BooleanField(default=False, verbose_name='PhD'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='provider',
            field=models.CharField(default='', max_length=100, verbose_name='Funding provider'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='science',
            field=models.BooleanField(default=False, verbose_name='Science'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='wir',
            field=models.BooleanField(default=False, verbose_name='Women in Research'),
        ),
    ]
