# Generated by Django 2.2.4 on 2019-10-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding_opportunity',
            name='description',
            field=models.TextField(),
        ),
    ]
