# Generated by Django 2.2.4 on 2019-08-30 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boolean_tags',
            name='id',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='id',
        ),
        migrations.AlterField(
            model_name='boolean_tags',
            name='Funding_Opportunity1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='boards.Funding_Opportunity1'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='Funding_Opportunity1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='boards.Funding_Opportunity1'),
        ),
    ]
