# Generated by Django 2.2.4 on 2019-10-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0002_auto_20191001_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding_opportunity',
            name='open_close',
            field=models.BooleanField(default=False),
        ),
    ]
