# Generated by Django 2.2.4 on 2019-10-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0002_auto_20191011_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding_opportunity',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('Y', 'year'), ('M', 'month')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='forecast_month',
            field=models.CharField(blank=True, choices=[('1', 'Jan'), ('2', 'Feb'), ('3', 'Mar'), ('4', 'Apr'), ('5', 'May'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'Aug'), ('9', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], max_length=15, null=True, verbose_name='Forecast Month'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='max_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max Amount'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='max_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max Duration'),
        ),
    ]
