# Generated by Django 2.2.4 on 2019-08-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20190831_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding_opportunity1',
            name='Creation_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
