# Generated by Django 2.2.4 on 2019-09-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0002_auto_20190916_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='important_date',
            options={'ordering': ['-date'], 'verbose_name': 'Important Dates', 'verbose_name_plural': 'Important Dates'},
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='closing_date',
            field=models.DateTimeField(verbose_name='Closing Date'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='duration_type',
            field=models.CharField(choices=[('Y', 'year'), ('M', 'month')], max_length=6, verbose_name='Duration Type'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Hide from regular view'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='limit_per_uni',
            field=models.BooleanField(default=False, verbose_name='Limited Per University'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='max_amount',
            field=models.PositiveIntegerField(blank=True, verbose_name='Max Amount'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='max_duration',
            field=models.PositiveIntegerField(blank=True, verbose_name='Duration Length'),
        ),
    ]
