# Generated by Django 2.2.4 on 2019-09-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0003_auto_20190908_0559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
