# Generated by Django 2.2.4 on 2019-10-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0003_funding_opportunity_open_close'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funding_opportunity',
            old_name='EOI_deadline',
            new_name='eoi_deadline',
        ),
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='External_deadline',
        ),
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='Forecast_Month',
        ),
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='Internal_deadline',
        ),
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='Minimum_data_deadline',
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='external_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='External_deadline'),
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='forecast_Month',
            field=models.CharField(blank=True, choices=[('1', 'Jan'), ('2', 'Feb'), ('3', 'Mar'), ('4', 'Apr'), ('5', 'May'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'Aug'), ('9', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], max_length=15, verbose_name='Forecast_Month'),
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='internal_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Internal_deadline'),
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='minimum_data_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Minimum_data_deadline'),
        ),
    ]
