# Generated by Django 2.2.4 on 2019-10-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0003_funding_opportunity_fable'),
        ('fodb', '0003_auto_20190916_1137'),
    ]

    operations = [
    ]
