# Generated by Django 2.2.4 on 2019-10-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0004_auto_20191003_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funding_opportunity',
            old_name='forecast_Month',
            new_name='forecast_month',
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='provider',
            field=models.CharField(default='', max_length=100, verbose_name='Funding provider'),
        ),
    ]
