# Generated by Django 2.2.4 on 2019-09-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0004_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding_opportunity',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
