# Generated by Django 2.2.4 on 2019-09-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0005_funding_opportunity_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding_opportunity',
            name='duration_type',
            field=models.CharField(choices=[('Y', 'Year'), ('M', 'Month')], default='Month', max_length=6),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='herdc',
            field=models.CharField(blank=True, choices=[('1', 'category1'), ('2', 'category2'), ('3', 'category3'), ('4', 'category4')], max_length=15),
        ),
    ]
