# Generated by Django 2.2.4 on 2019-10-08 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0005_auto_20191003_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='closing_date',
        ),
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='external_deadline',
        ),
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='internal_deadline',
        ),
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='open_close',
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='application_open_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Application Open Date'),
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='external_submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='External Submission Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='internal_submission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Internal deadline'),
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='is_visiable',
            field=models.BooleanField(default=True, verbose_name='Visiable from regualr view'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='forecast_month',
            field=models.CharField(blank=True, choices=[('1', 'Jan'), ('2', 'Feb'), ('3', 'Mar'), ('4', 'Apr'), ('5', 'May'), ('6', 'Jun'), ('7', 'Jul'), ('8', 'Aug'), ('9', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], max_length=15, verbose_name='Forecast Month'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='link',
            field=models.URLField(max_length=260, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='max_amount',
            field=models.IntegerField(blank=True, verbose_name='Max Amount'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='max_duration',
            field=models.IntegerField(blank=True, verbose_name='Max Duration'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='minimum_data_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Minimum data deadline'),
        ),
    ]
