# Generated by Django 2.2.4 on 2019-10-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0006_auto_20191008_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='visiting',
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='visiting_fellow',
            field=models.BooleanField(default=False, verbose_name='Visiting Fellow'),
        ),
    ]
