# Generated by Django 2.2.4 on 2019-10-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0006_auto_20191008_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding_opportunity',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('Y', 'year'), ('M', 'month')], max_length=6),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='is_visiable',
            field=models.BooleanField(default=True, verbose_name='Visiable in regualr view'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='max_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max Amount'),
        ),
        migrations.AlterField(
            model_name='funding_opportunity',
            name='max_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max Duration'),
        ),
    ]
