# Generated by Django 2.2.4 on 2019-10-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0007_auto_20191008_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding_opportunity',
            name='is_visiable',
        ),
        migrations.AddField(
            model_name='funding_opportunity',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible from regualr view'),
        ),
    ]
