# Generated by Django 2.2.4 on 2019-10-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0010_auto_20191009_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding_opportunity',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('Y', 'year'), ('M', 'month')], max_length=6),
        ),
    ]
