# Generated by Django 2.2.5 on 2019-09-08 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fodb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importantdate',
            old_name='date_dtatus',
            new_name='date_status',
        ),
        migrations.RenameField(
            model_name='importantdate',
            old_name='funding_opportunity_id',
            new_name='funding_opportunity',
        ),
    ]
